# ===============================================
# = CONFIGURATION DU SERVER WEB EMBARQUE TOMCAT =
# ===============================================
server:
  port: 9000

# ======================================
# = CONFIGURATION DE LA JOURNALISATION =
# ======================================
logging:
  level:
    # Permet de voir dans la console le port utilisé par Tomcat au démarrage
    org.springframework.boot.web.embedded.tomcat: INFO
    root: INFO
    com.api: DEBUG

spring:
  # ============================================
  # = CONFIGURATION DE LA SOURCE DE DONNEE MySQL =
  # ============================================
  datasource:
    url: jdbc:mysql://localhost:3306/dvdstore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # ===========================================================
  # = CONFIGURATION DES PROPRIETES JPA (Java Persistence API) =
  # ===========================================================
  jpa:
    hibernate:
      ddl-auto: create-drop
    # Différer l’initialisation de notre source de données.
    defer-datasource-initialization: true
    show-sql: true
  #  Pour l’insertion de données via des données.sql, nous devons définir la propriété
  sql:
    init:
      mode: always


