# ===============================================
# = CONFIGURATION DU SERVER WEB EMBARQUE TOMCAT =
# ===============================================
server:
  port: 9000

# ======================================
# = CONFIGURATION DE LA JOURNALISATION =
# ======================================
logging:
  level:
    # Permet de voir dans la console le port utilisé par Tomcat au démarrage
    org.springframework.boot.web.embedded.tomcat: INFO
    root: INFO
    com.api: DEBUG

spring:
  # ============================================
  # = CONFIGURATION DE LA SOURCE DE DONNEE MySQL =
  # ============================================
  datasource:
    url: jdbc:mysql://localhost:3306/dvdstore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  exécute le fichier data.sql lors du démarrage de votre application: always / never
    initialization-mode: always
    #  spécifiez le chemin du fichier data.sql dans l'application Spring Boot
    #data: classpath:database.sql

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  # ===========================================================
  # = CONFIGURATION DES PROPRIETES JPA (Java Persistence API) =
  # ===========================================================
  jpa:
    hibernate:
      ddl-auto: update
    # Différer l’initialisation de notre source de données.
    defer-datasource-initialization: true
    show-sql: true
  #  Pour l’insertion de données via des données.sql, nous devons définir la propriété
  sql:
    init:
      mode: always

#"${jwt.signing.key}" = signingKey
jwt:
  signing:
    key: signingKey



